---
- name: Add Syncthing APT repository
  deb822_repository:
    name: syncthing
    types: deb
    uris: https://apt.syncthing.net/
    suites: syncthing
    components: stable-v2
    signed_by: https://syncthing.net/release-key.gpg
    install_python_debian: yes
  register: _syncthing_repo

- name: Install Syncthing
  apt:
    name: syncthing
    state: present
    update_cache: "{{ _syncthing_repo.changed }}"

- name: "{{ syncthing_enable_service | ternary('Enable', 'Disable') }} syncthing systemd service for user {{ syncthing_user }}"
  service:
    name: syncthing@{{ syncthing_user }}
    state: "{{ syncthing_enable_service | ternary('started', 'stopped') }}"
    enabled: "{{ syncthing_enable_service }}"
  when: syncthing_user | length > 0
